### ISSUE TITLE
TreeDefinitions - If DataElements is first element - Children not displaying

### ISSUE THREAD

**Issue by aeont** [Orckestra/CMS-Foundation#13]
![capture](https://cloud.githubusercontent.com/assets/11037398/10763694/328c2422-7c88-11e5-9602-d6fad1039942.PNG)

In situations where I have DataElements as first element in my tree - it's childrens is not displaying. Workaround is add extra level (Element) and use DataElements as it's children OR write C# - which is not convenient for such simple stuff. See code below: 

![capture1](https://cloud.githubusercontent.com/assets/11037398/10763862/ce589282-7c88-11e5-93ce-fcd047bcb17b.PNG)

**Comment by aeont** [comment]
I.e. I can't have tree like this:

ClientInfo.xml
  Client1
  Client2

Just like this:

Clients <--- extra level (workaround)
 ClientInfo.xml
  Client1
  Client2

**Comment by kasravi** [comment]
actual bug: when data elements placed at the root of tree children won't show up

**Comment by wwwysocki** [comment]
Verified in "dev" (20161004.1)
