### ISSUE TITLE
Adding a Razor Function using different casing for existing namespace yield error dialog, prevents focus and auto edit

### ISSUE THREAD

**Issue by mawtex** [Orckestra/CMS-Foundation#168]
Repro:

1) Add a Razor function with namespace "A" and name "First"
2) Add a Razor function with namespace "a" and name "Second"

Expected: Both actions end up with Razor Function editor for the newly created function.

Actual: The function is created, but you get an error dialog with exception (detailing that Razor Function a.Second was not found, happening while workflow tries to focus the added element in tree). 

Issue: Razor Functions rely on a folder structure on disk to represent namespace and writing the file a/Second.cshtml works (creating the file in A/Second.cshtml, since Windows paths are case insensitive and folder A already exists). The Razor Function provider picks up the function name A.Second so a query for a.second fails.

Workaround: Close the error dialog, select the function in the tree and edit it.

Exception in C1 Log: The Function named 'a.Second' is not known. Ensure it exists with the exact spelling and casing you provided.

**Comment by wwwysocki** [comment]
Verified on https://github.com/Orckestra/CMS-Foundation/releases/tag/v5.4
