### ISSUE TITLE
After call to GlobalEventSystemFacade.FlushTheSystem() TreeDefinition security ancestor providers are (seemingly) not properly re-initialized

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/CMS-Foundation#177]
**Repro**:

1. [Download the Composite.Tests.AttachedElements package](https://dl.dropboxusercontent.com/u/11887629/Composite.Tests.AttachedElements.zip).
2. Install the package
3. In the "Content" perspective, look for the new node "Page state overview" (see the screenshot below).
 
**Expected**: The node appears in the tree (normally, at the bottom).

**Actual**: The node doesn't appear in the tree. (The element is “in there”, but the security system does not find a valid path from the root to the element from your provider.)
 
If you restart the system, all work fine (until the next time you do a `GlobalEventSystemFacade.FlushTheSystem()`)

![page-state-overview-element-attached](https://cloud.githubusercontent.com/assets/14821915/15426913/374f1762-1e9a-11e6-8dfb-54577c10e56b.png)

**Comment by kasravi** [comment]
not an actual bug. when adding auxiliary ancestor provider unless explicitly stated it would not be considered flush persistent.
using
`AuxiliarySecurityAncestorFacade.AddAuxiliaryAncestorProvider<MyRootEntityToken>(new MyRootEntityTokenAuxiliarySecurityAncestorProvider(),true); `
instead of
               ` AuxiliarySecurityAncestorFacade.AddAuxiliaryAncestorProvider<MyRootEntityToken>(new MyRootEntityTokenAuxiliarySecurityAncestorProvider());`

would prevent this issue

**Comment by mawtex** [comment]
Also, subscribing to flush events and registering again is a fix.
