### ISSUE TITLE
MultiKeySelector in compact mode no longer preserve selection order

### ISSUE THREAD

**Issue by npwaa** [Orckestra/CMS-Foundation#186]
This was broken in changeset 27dfb0cf66652c2a42d4cde23988cf1ad6547f14
because options in compact mode are no longer reordered with selected options on top in selected order.

If you use this control on page metadata tab, the selection is reordered if you save the page even if you never switch to the metadata tab.

**Comment by aeont** [comment]
@mawtex @wwwysocki  I didn't experienced issue described, but I would like to point to similar problem, probably separate issue needs to be opened:

[FunctionParameter(Label = "Statuses ", Help = "Statuses ", DefaultValue = null, WidgetMarkup = @"<f:widgetfunction xmlns:f=""http://www.composite.net/ns/function/1.0"" name=""Composite.Widgets.String.DataIdMultiSelector""><f:param name=""OptionsType"" value=""Aeont.Data.Types.IStatus"" /><f:param name=""CompactMode"" value=""False"" /></f:widgetfunction>")]
    public List<string> Statuses { get; set; }

This markup in Razor functions works fine, saves data to the page, but when I open it's not keep selected values.

Second: 
public List<Guid>  Statuses { get; set; }
would be also nice to have, together with 
public List<Aeont.Data.Types.IStatus> Statuses { get; set; }

It's not something critical really, but helps save few lines of code.

**Comment by npwaa** [comment]
The described issue is real. i have crated a test function in your style, and retestet it on latest dev build.

create test razor function test.sort with parameter

`[FunctionParameter(DefaultValue = null, WidgetMarkup = @"
<f:widgetfunction xmlns:f=""http://www.composite.net/ns/function/1.0"" name=""Composite.Widgets.String.Selector""><f:param name=""Options""><f:function name=""Composite.Utils.String.Split""><f:param name=""String"" value=""1,2,3"" /></f:function></f:param><f:param name=""Multiple"" value=""true"" /><f:param name=""Compact"" value=""true"" /></f:widgetfunction>")]
    public string Items { get; set; }`

insert it on a page

`
<f:function name="test.sort" xmlns:f="http://www.composite.net/ns/function/1.0">
	<f:param name="Items" value="3,2,1" />
</f:function>
`

edit and ok and  function on page is now

`
<f:function name="test.sort" xmlns:f="http://www.composite.net/ns/function/1.0">
	<f:param name="Items" value="1,2,3" />
</f:function>
`

NB i solves it by added this to \Composite\controls\FormsControls\FormUiControlTemplates\Selectors\MultiKeySelector.ascx
`
protected new List<KeyLabelPair> GetOptions()
    {
        var options = base.GetOptions();

        if (CompactMode)
        {
            var selectedOptions = new List<KeyLabelPair>();
            foreach (string key in _selectedKeys)
            {
                var selectedOption = options.FirstOrDefault(f => f.Key == key);
                if (selectedOption != null)
                {
                    selectedOptions.Add(selectedOption);
                }
            }

            var unselectedOptions = options.Where(o => !_selectedKeys.Contains(o.Key));

            options = selectedOptions.Concat(unselectedOptions).ToList();
        }

        return options;
    }`

not a prety solutin, but easy to maintain

**Comment by napernik** [comment]
@aeont please register a separate issue for the described problem

**Comment by napernik** [comment]
Fixed in the "fix-bugs" branch

**Comment by wwwysocki** [comment]
> MultiKeySelector in compact mode no longer preserve selection order
The fix verified in "fix-bugs" (20161003.4)
