### ISSUE TITLE
An error occurs with a message broadcast without the message body in the C1 Console

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/CMS-Foundation#220]
**Repro**:

1. In the C1 Console, click the "Settings" (gear) button, then - "Broadcast Message".
2. In the popup window, enter some text in the Title field.
3. Keep the Message field blank - don't enter anything there.
4. Send the message.

**Expected**: The message should pop up without the message body.
**Actual**: An error message pops up:

![broadcast-message-error](https://cloud.githubusercontent.com/assets/14821915/18272808/972175d8-7442-11e6-9dc3-e40de83e0218.png)

**Comment by kasravi** [comment]
fixed

**Comment by wwwysocki** [comment]
Verified in "fix-bugs" (20161003.4)
