### ISSUE TITLE
Upgrade to 5.2 - presense of existing dynamic page meta data types causes YSOD on startup

### ISSUE THREAD

**Issue by napernik** [Orckestra/CMS-Foundation#227]
Repro:
1) Have a website with C1 version 5.0 or 5.1
2) Create a dynamic page meta data type
3) Install an upgrade package
Result: YSOD

The reason for the exception is that we have to code to auto update schema for static data types, but not for dynamic ones. After the upgrade page meta types will have no VersionId field, inherited from IPageMetaData -> IVerisioned.

**Comment by wwwysocki** [comment]
Verified with "fix-bugs" (20161003.4) on 5.0 and 5.1
