### ISSUE TITLE
Saving a page does not update page browser if the page was in "draft" state beforehand

### ISSUE THREAD

**Issue by napernik** [Orckestra/CMS-Foundation#228]
Repro:
1) Open a C1 page for editing
2) Make some changes, click "Save" (not "Save & Publish")
3) Go to the console browser, to see the preview of the page's content 
4) Go back to the editor, make a change and click "Save"
5) Go back to the console browser
Expected: the content changes are visible
Actual: no changes are displayed

**Comment by napernik** [comment]
Fixed in "fix-bugs" branch

**Comment by wwwysocki** [comment]
Verified in "fix-bugs" (20161003.4)
