### ISSUE TITLE
[5.2+] Can't change the page type on pages

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/CMS-Foundation#231]
**Repro**:

1. Create two page types with default settings: "Test1" and "Test2".
2. Create a page (below the front page) of the page type "Test1".
3. Open the Settings tab of the page opened in the editor.
4. Try and switch the page type to "Test2"

**Expected**: You can select the "Test2" page type in the dropdown menu and switch to it.
**Actual**: Only the "Test1" page type is available on the drop down menu. You can't switch page types at all.

**Note**: You can only select and switch page types on the home pages (Level 1). 

![cant-switch-page-types](https://cloud.githubusercontent.com/assets/14821915/18706256/eb26bd38-7ff9-11e6-8a27-a5751ef4d914.png)

**Comment by mawtex** [comment]
Lowering the severity because not a very used scenario and there is a possible workaround (re-create page with desired type).

**Comment by napernik** [comment]
Fixed in the "fix-bugs" branch

**Comment by wwwysocki** [comment]
Verified in "fix-bugs" (20161003.4)
