### ISSUE TITLE
An exception in routing code when making requests to a language without publishined pages

### ISSUE THREAD

**Issue by napernik** [Orckestra/CMS-Foundation#241]
Repro:
1) Add a new language to C1, f.e. "French" with url mapping "fr"
2) Make a request to <site url>/fr/qwertyui
Expected result: 404 response
Actual result: YSOD

> [NullReferenceException: Object reference not set to an instance of an object.]
   Composite.Plugins.Routing.Pages.DefaultPageUrlProvider.TryGetPageByUrlTitlePath(String pagePath, Boolean pathInfoExtracted, IHostnameBinding hostnameBinding, String& pathInfo) +1073
   Composite.Plugins.Routing.Pages.DefaultPageUrlProvider.ParsePagePath(String pagePath, PublicationScope publicationScope, CultureInfo locale, IHostnameBinding hostnameBinding) +725
   Composite.Plugins.Routing.Pages.DefaultPageUrlProvider.ParseUrl(String relativeUrl, UrlSpace urlSpace, UrlKind& urlKind) +1261
   Composite.Plugins.Routing.Pages.DefaultPageUrlProvider.ParseUrl(String absoluteUrl, UrlKind& urlKind) +818
   Composite.Core.Routing.Pages.C1PageRoute.GetRouteData(HttpContextBase context) +457
   System.Web.Routing.RouteCollection.GetRouteData(HttpContextBase httpContext) +230
   System.Web.Routing.UrlRoutingModule.PostResolveRequestCache(HttpContextBase context) +72
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +141
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +91

**Comment by napernik** [comment]
Fixed in "fix-bugs" branch

**Comment by wwwysocki** [comment]
Verified in "fix-bugs" (20161003.4)
