### ISSUE TITLE
Certain packages containing dynamic data types may hang during install

### ISSUE THREAD

**Issue by mawtex** [Orckestra/CMS-Foundation#282]
Repro:

1) Install attached package as a local package

Expected: Installs within a few seconds
Actual: The install process hang (due to dead lock)
[Orckestra.Lists.FAQ.zip](https://github.com/Orckestra/CMS-Foundation/files/555624/Orckestra.Lists.FAQ.zip)

**Comment by wwwysocki** [comment]
Verified on https://github.com/Orckestra/CMS-Foundation/releases/tag/v5.4
