### ISSUE TITLE
CMS Package, data installer, using allowOverwrite fail for data not already existing

### ISSUE THREAD

**Issue by mawtex** [Orckestra/CMS-Foundation#297]
The allowOverwrite attribute which you can set on <Type /> elements for DataPackageFragmentInstaller will cause an exception, if data being loaded is new (does not exist in the system already).

Repro:
1. Install attached Orckestra.Test.BeforeOverwriteData.zip as local package 
2. Install attached Orckestra.Test.OverwriteData.zip as local package 

Expected:
In step 1, we install 3 data elements (Item 1, Item 3, Item 4).
In step 2, we update "Item 3" and add new data element "Item 2"

Actual: 
Package install fail in step 2 with "Non-static method requires a target" error text.

[Orckestra.Test.BeforeOverwriteData.zip](https://github.com/Orckestra/CMS-Foundation/files/580789/Orckestra.Test.BeforeOverwriteData.zip)
[Orckestra.Test.OverwriteData.zip](https://github.com/Orckestra/CMS-Foundation/files/580790/Orckestra.Test.OverwriteData.zip)

Sample use of the allowOverwrite  attribute:

	<mi:PackageFragmentInstallers>
		<mi:Add installerType="Composite.Core.PackageSystem.PackageFragmentInstallers.DataPackageFragmentInstaller, Composite" uninstallerType="Composite.Core.PackageSystem.PackageFragmentInstallers.DataPackageFragmentUninstaller, Composite">
			<Types>
				<Type type="Orckestra.Test.Data" allowOverwrite="true">
					<Data dataScopeIdentifier="public" dataFilename="~\Datas\Orckestra.Test.Datas_public.xml" />
				</Type>
			</Types>
		</mi:Add>
	</mi:PackageFragmentInstallers>

**Comment by wwwysocki** [comment]
Verified in 20161109.3 (fix-bugs)
