### ISSUE TITLE
Question: How can you change a Global Datatype into a Page Datafolder?

### ISSUE THREAD

**Issue by DBailey635** [Orckestra/CMS-Foundation#310]
Is it possible to change a Global Datatype into a Page Datafolder? On the surface and in the main XML file, they appear almost identical. If yes, how do you do it?

**Comment by burningice2866** [comment]
@DBailey635 Page Datafolders are datatypes which implement the `IPageDataFolder` interface, and Page Metadata implement `IPageMetaData`. If a type doesn't implement one of these interfaces its considered a Global Datatype.

You can therefor easily change a Global Datatype into a Page Datafolder by implementing `IPageDataFolder`, like this

Before
```
public interface MyDataType : IData
{ 
   ... 
}
```

After
```
public interface MyDataType : IPageDataFolder
{ 
   ... 
}
```

**Comment by DBailey635** [comment]
Thanks @burningice2866.

So, if I edit ~/App_Data/Composite/DataMetaData/[typename-GUID].xml to change:

`<SuperInterfaces/>`

... to:

```
<SuperInterfaces>
    <SuperInterface type="Composite.Data.IPageDataFolder,Composite" />
    <SuperInterface type="Composite.Data.IPageRelatedData,Composite" />
</SuperInterfaces>
```

... and restart the server, will that do the trick?

**Comment by burningice2866** [comment]
@DBailey635 yeah, that should do the trick.

The reason you're seeing both `IPageDataFolder` and `IPageRelatedData` in the list of SuperInterfaces, is because `IPageDataFolder` implements `IPageRelatedData`, and the way C1 stores the DataMetaData is by flatting out the whole hierarchy of who implements what.
