### ISSUE TITLE
Feature Request: Non-static WidgetFactoryMethod 

### ISSUE THREAD

**Issue by ai-fwd** [Orckestra/CMS-Foundation#314]
Is it possible to provide a way to support a non-static WidgetFactoryMethod? Or have the WidgetFactoryClass implementation use reflection to check the actual class type before invoking the static WidgetFactoryMethod?

Scenario: Create a base class RazorFunction that has a parameter that will be a dropdown. Create multiple subclasses that can each define the dropdown options.

Currently there is no way to provide the options because the WidgetFunctionProvider is static. Even when you tell the compiler to replace it via the "new" keyword in the subclass it still defaults to the base class implementation.

The only way around this is to declare that parameter on every derived class and exclude it from the base class. This is repetitive and can't be enforced via any design pattern.

**Comment by burningice2866** [comment]
@ai-fwd what version of the CMS are you using? I have a feature in the Community Edition which allows for this by having a virtual method on the `RazorFunction` class that returns a Dictionary of Widgets where the key correspond to the the properties you want to define widgets for.

**Comment by ai-fwd** [comment]
@burningice2866 I'm using v4.3 of the Community Edition. Do you have the feature you've implemented available in your bitbucket?

**Comment by burningice2866** [comment]
@ai-fwd ah... i have it in version 5.1, reason i asked what version you used was that i was concerned that you was on a never version than 5.1.

I can backport it to the 4.3 version though, no big deal. The feature was originally a part of the first version of Razor Functions which was developed and maintained by me, but didn't make it when it was taken over by Composite and baked into C1. You can see the old original code here https://github.com/burningice2866/CompositeC1Contrib/blob/master/Core/FunctionProvider/FileBasedFunctionProvider.cs#L146

**Comment by ai-fwd** [comment]
@burningice2866 i'm happy to take a stab at back porting it if you can provide a link to your 5.1 implementation.

**Comment by burningice2866** [comment]
@ai-fwd like i said, its no big deal.... so here you go :) https://github.com/burningice2866/C1-CMS/commit/6eb0d904d05f973dde1555509427918e9ec718a7

**Comment by ai-fwd** [comment]
@burningice2866 your commit worked perfectly! I had to change the return of GetParameterWidgets to an empty instance of ParameterWidgets otherwise we'd be checking Contains on a null instance but other than that it was great. 

My solution still fell down because StandardWidgetFunctions.DropDownList still wanted a static method to get the options but what you're solution gave me was a way to at least determine the baseType and call it. 

There is still no way to enforce the static method exists via any pattern but that's a problem for another day.

**Comment by burningice2866** [comment]
@ai-fwd bam, you're right... strange i haven't experienced that before. I'll fix it right away

Regarding selector-functions taking a datasource, its true that they all rely on Static Method Calls. In a way it makes sense, since the Console when building the UI Markup doesn't have any context, in the end `StandardWidgetFunctions.DropDownList` is simply emitting some xml which the Workflow engine can parse and create a UI from. There is no reference back to the originating definer at this point.

What i've done at times, is to take advantage of the fact that you can pass parameters to the Static Method Call - that way you can call a Wrapper Method with a type as argument, and then instantiate that type, call a method and return that data from your Static Method.

**Comment by ai-fwd** [comment]
@burningice2866 yes that's a nice abstraction. A bit much in my particular scenario but i'll remember that for next time.

Is it worthwhile to keep this as an open feature request or should i close it off since there is a viable workaround?

**Comment by burningice2866** [comment]
@ai-fwd hard to say... its curious that there hasn't been a single comment from the Core Team, by IMO you should leave the feature request open, but with the comment history referring to that the feature exists in Community Edition.

**Comment by burningice2866** [comment]
@ai-fwd i created a pull request here which you're welcome to like https://github.com/Orckestra/CMS-Foundation/pull/315

**Comment by mawtex** [comment]
Merged to vnext-dev - thanks!

So, now (on Razor Functions and User Control Functions) you can omit defining widgets via the `[FunctionParameter()]` attribute and instead define them by returning a [parameter name / widget provider] dictionary, like this: 

```
public override IDictionary<string, WidgetFunctionProvider> GetParameterWidgets()
{
    return new Dictionary<string, WidgetFunctionProvider>
    {
        { nameof(Article), StandardWidgetFunctions.TextAreaWidget }
    };
}
```
