### ISSUE TITLE
Question: Are Orckestra still working through issues and feature requests over on Codeplex?

### ISSUE THREAD

**Issue by DBailey635** [Orckestra/CMS-Foundation#322]
Just wondering if the team is still working though all of the issues over on [Codeplex](https://orckestracms.codeplex.com/)?  If not, should we transfer still-relevant issues to GitHub now (closing them on Codeplex once transfered)?

**Comment by mawtex** [comment]
Please do - we are only keeping an eye on the forum there.

**Comment by DBailey635** [comment]
Thanks. Am going to start working on this. Only thing is, I can't close issues on Codeplex... even the ones I created... so someone from Orckestra will need to do so once we've marked something as copied across.
