### ISSUE TITLE
Inconsistent use of the names for the "container class(es)" attribute

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/CMS-Foundation#344]
1. Check the names for the "pal"-prefixed attributes in component XML files (pal:container-anti-class="" 	pal:container-class=""). Note the singular in use
2. Check the name for the attribute to be used on a template's placeholder (ContainerClasses="") and and a label on page type's placeholder content element ("Container Classes"). Note the plural in use.
3. Check the name and label for the parameter of the Composite.Widgets.String.VisualXhtmlEditor widget function (ContainerClasses). Note the plural in use.

**Expected**: Either the singular or the plural should be used everywhere.
**Actual**: Both the singular and the plural are used in different places

**Comment by kasravi** [comment]
Correct, and using plural form is closer to the intended use

**Comment by wwwysocki** [comment]
Verified in 20170124.2
