### ISSUE TITLE
Select Component window is blank on IE11

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/CMS-Foundation#352]
**Repro**:

1. Use IE11.
2. Edit a page.
3. Click the "Components" button, or "Insert" > "Component".
4. Check the window that pops up.

**Expected**:  The window shows available components to insert.
**Actual**: The window is blank.

**Note**: It most likely occurs on the "compiled" version (as opposed to the "developer" one).

**Workaround**: Use a different browser.

![no-select-component-on-ie11](https://cloud.githubusercontent.com/assets/14821915/22142479/06d37062-deff-11e6-8d6f-81a3eb856451.png)

**Comment by gertsonderby** [comment]
A previously inserted capture for this error has gone missing. (IE11 does not support Promises, other expected ES2015 features, so needs extra polyfills.) Will find and reinstate.

**Comment by gertsonderby** [comment]
Should be fixed as of next build.

**Comment by wwwysocki** [comment]
Verified on 20170124.2
