### ISSUE TITLE
[Components] The Components button is enabled even though there is no focus in the editing area

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/CMS-Foundation#356]
**Repro**:

1. Edit a page.
2. Make sure the default focus is still there (not in the editing area of Visual Editor).
3. Try and click the "Components" button.

**Expected**: If there is no focus in the editing area, the button must be disabled.

**Actual**: The button is always enabled and you can try and click it to no effect. The user experience here is very poor.

**Note**: This might be a more general (Core) issue, that buttons are enabled when there is no focus in the editing area.

**Comment by mawtex** [comment]
Relating to this is that the visual editor is currently "losing focus" very easily.

Like:

1) Mark a word, press the "bold" button, 
2) type text or use arrow key to move carret

Expected: writing text, arrow buttons picked up by Visual Editor. Carret position where user left it (or after newly inserted item)
Actual: no focus on visual editor. User need to use mouse to re-focus editor at desired location.

Also same problem after inserting an image, a component and probably all other toolbar actions.

**Comment by kasravi** [comment]
Also worth mentioning it is not only Components button that doesn't not look disabled. when you open the edit page none of the buttons in toolbar is enabled except undo. but none of them are shown as disabled.

How does it look like now:
![image](https://cloud.githubusercontent.com/assets/10363073/22370678/eb73904c-e492-11e6-8c77-50a6aac56def.png)

How it behaves ( so better to look accordingly)
![image](https://cloud.githubusercontent.com/assets/10363073/22370708/0d0b6f86-e493-11e6-8e86-0c3c08470452.png)

**Comment by wwwysocki** [comment]
Everything reported here above is fixed now (verified on 20170130.4)

Except for:

>Also same problem after inserting an image, a component and probably all other toolbar actions.

I've created a separate issue for that: https://github.com/Orckestra/CMS-Foundation/issues/375

Please continue there
