### ISSUE TITLE
The Select Components window allows a (pseudo-)multiple selection

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/CMS-Foundation#357]
**Summary**:

Because a component can be listed under more than one category due to multiple tags in pal:tags, when you select such a component in the "Select Component" window, you can see it selected elsewhere among other components, which actually puzzles/misleads at first :) - "what's happening?"

It doesn't affect anything, only looks [subjectively] unusual.

**Prepare**:

* Set one of the components to appear in two categories (desireably in alphabetically close categories), for example: pal:tags="a,b,c".

**Repro**:

1. Edit a page.
2. Insert > Component
3. Select the component listed in multiple categories.

**Expected**: Only the clicked (selected) appears as focused (selected) in the list.
**Actual**: All the instances of the same component get selected.

![multiple-selection-in-components](https://cloud.githubusercontent.com/assets/14821915/22147383/0ad5c22a-df11-11e6-9721-d6d74acafbd6.png)

**Comment by gertsonderby** [comment]
This would be difficult to fix. Not impossible, just probably not worth the work. It is mildly confusing at first, but generally only if you have few components shown (i.e. same components shown multiple times in same screen without scrolling). I would say we leave it be.

**Comment by wwwysocki** [comment]
By design
