### ISSUE TITLE
[Components] IE11: The Backspace and other non-alphanumeric keys not working in the Filter field

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/CMS-Foundation#364]
**Repro**:

1. Use IE11
2. Insert > Component
3. Type something in the Filter field (top right).
4. Press BACKSPACE to delete the typed term end-to-start.

**Expected**: You can delete characters with by pressing BACKSPACE.
**Actual**: You can't delete characters

**Workaround**: Use a different browser

Please also see Issue https://github.com/Orckestra/CMS-Foundation/issues/373. They seem related

**Comment by gertsonderby** [comment]
I cannot reproduce this bug. Steps as provided produce expected result in both dev and bundled version.

**Comment by wwwysocki** [comment]
Tried on 20170130.2 (6.0.6239.20582). Now it's even worse in my case:

* I can only type in alphanumerical characters (A..Z,a..z,0..9)
* I can't type in a space, can't use arrows to move backward/forward, can't use DEL or BACKSPACE etc

It feels like some kind of filter has been applied on what charecters can be inserted here.
I manage to reproduce it on a totally different PC (@neexite 's)

**Comment by gertsonderby** [comment]
This issue is the same as #373. I suggest we move the discussion there.

**Comment by gertsonderby** [comment]
Fixed by @neexite in c7550e4.

**Comment by wwwysocki** [comment]
Verified on 20170131.5 (dev)
