### ISSUE TITLE
[Components] IE11: No update in the Grid when you remove a filter

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/CMS-Foundation#365]
**Repro**:

1. Use IE11
2. Insert > Component
3. Type "aaaa" (or anything that will hide **all** the components) in the Filter field (top right).
4. Click the 'X' button in the right part of the Filter field.

**Expected**: All the components re-appear in the grid.
**Actual**: Still no components

**Workaround**: Use a different browser

![image](https://cloud.githubusercontent.com/assets/14821915/22284143/78260534-e2ee-11e6-915a-9ccf6b466e69.png)

**Comment by gertsonderby** [comment]
This is waiting on facebook/react#8575, which fixes facebook/react#6822. I've got a possible workaround, which I will work on implementing.

**Comment by gertsonderby** [comment]
Workaround is in place.

**Comment by wwwysocki** [comment]
Verified on 20170130.4
