### ISSUE TITLE
Error after upgrading from 5.0 to 5.5

### ISSUE THREAD

**Issue by olihofmann** [Orckestra/CMS-Foundation#369]
Hi,

I have made the upgrade to the version 5.5. After the upgrade i have the follwing error
**Missing 'VersionId' attribute in a data store file.**
I delete the IPage and the IPagePlaceholderContent XML Files. After thar everything was correct. But i
dont can delete this files, we have existing content.

Can anyone help me resolve this?

Regards,
Oli

**Comment by burningice2866** [comment]
You should open the xml-files and add a new `VersionId=""` attribute to each record by hand.

As far as i can see, the value of VersionId needs to be a unique guid, so unless you have VS + Resharper, its going to be a tedious task, copy-pasting guid from here https://www.guidgenerator.com/

**Comment by burningice2866** [comment]
Actually it looks like here https://github.com/Orckestra/CMS-Foundation/blob/1dfab411e5607d7c5e3acc7cd48874d28e6cd5e7/Composite/Data/Types/IVersionedDataHelper.cs#L46 that C1 will take care of empty guid and "upgrade" them, so it should be enough to add the following attribute to each record

`VersionId="00000000-0000-0000-0000-000000000000"`

**Comment by olihofmann** [comment]
Thanks for your fast answer. 

Is it not possible that C1 add this Attribute if it's missing?

**Comment by burningice2866** [comment]
Nope... hence the error you're getting.

Thats the tradeoff between using the Upgrade Package provided by Orckestra and upgrading manually by hand.
