### ISSUE TITLE
[Console Search] Chrome & Firefox: Clicking a link in the search adds # to the URL

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/CMS-Foundation#371]
**Repro**:

1. Use Chrome or Firefox.
2. Search for something to get some pages in search results.
3. Click the link of the page in the results.
4. Check the URL in the Address bar of your browser.

**Expected**: The URL remains unchanged.
**Actual**: The URL have # appended (e.g. http://contoso.com/Composite/top.aspx#)

Please see also: Issue https://github.com/Orckestra/CMS-Foundation/issues/370

**Comment by gertsonderby** [comment]
All the new UI does with this link is to access it with target="_top". So I suspect this problem is in the old UI's reaction to it.

**Comment by wwwysocki** [comment]
Verified on 20170130.7
