### ISSUE TITLE
[Console Search] Firefox & IE11: Checkboxes in the filter pane look "old school"

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/CMS-Foundation#372]
**Repro**:

1. Use Firefox / Use IE11.
2. Search for something that will give you faceted search filter checkboxes, for example, "site" on "Venus".
3. Check the checkboxes. (Compare to those in some other places in the system, for example a checkbox field on a data form or in a function parameter in the same browser.)

**Expected**: The checkboxes look like those everywhere else in the CMS ("styled").
**Actual**: They look "old style" (see below).

**Firefox**:

![image](https://cloud.githubusercontent.com/assets/14821915/22335510/b744014a-e3e7-11e6-9281-1aefe5bcf48d.png)

**IE11**:

![image](https://cloud.githubusercontent.com/assets/14821915/22335581/e5163cbe-e3e7-11e6-9c06-239d9b833124.png)

**Comment by gertsonderby** [comment]
https://coderwall.com/p/a7tbrq/protip-if-you-want-to-style-checkboxes-radio-buttons-or-select-menus-in-firefox-don-t-bother <- Current situation. IE/Edge somehow also intractable to checkbox styling, while Chrome works fine. Working on a deeper fix for this, but for now, we have functionality and the checkboxes don't look _broken_ at least...

**Comment by gertsonderby** [comment]
Found a way to fix it that was fairly plug-and-play. So checkboxes on the console search branch should look to specification in all supported browsers.

**Comment by wwwysocki** [comment]
Verified on 20170130.2
