### ISSUE TITLE
[Console Search] IE11: The Backspace and many other non-alphanumeric keys not working in the Search box.

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/CMS-Foundation#373]
**Notes**: 

* Looks related to Issue https://github.com/Orckestra/CMS-Foundation/issues/364 but, as that one, might be reporducible only on some environments.
* The exact setup for the 100% repro is currently unclear. 
* The build from the "**feature-console-search**" used.

**Repro**:

1. Use IE11.
2. The Search perspective > type in some search term. 
3. Press BACKSPACE to delete the typed term end-to-start.

**Expected**: You can delete characters by pressing BACKSPACE.
**Actual**: You can't delete characters.

**Workaround**: Use a different browser

IE 11 version:

![image](https://cloud.githubusercontent.com/assets/14821915/22363453/28ba668a-e473-11e6-96d4-0cc1635b501c.png)

**Comment by gertsonderby** [comment]
Should be fixable by cherry-picking fix for #364. I think.

**Comment by gertsonderby** [comment]
Can't replicate this, but am seeing something similar to #365 - though more subtle. Hopefully fixing this will also fix this...

**Comment by gertsonderby** [comment]
I _hope_ this fixes it, at least. If not, reopen.

**Comment by wwwysocki** [comment]
Tried on 20170130.2 (6.0.6239.20582). Now it's even worse in my case:

* I can only type in alphanumerical characters (A..Z,a..z,0..9)
* I can't type in a **space**, can't use **arrows** to move backward/forward, can't use DEL or BACKSPACE etc

It feels like some kind of filter has been applied on what charecters can be inserted here.
I manage to reproduce it on a totally different PC (@neexite 's)

**Comment by gertsonderby** [comment]
I am going to need very exacting detail here. I have tried and tried to replicate this in the very same IE11 version as reported, with production build or dev setup, and nothing. Everything works perfectly. #364 as well. It seems to be a general problem re. input fields.

**Comment by gertsonderby** [comment]
Aha! Got it replicated. Will come back with info as I find it.

**Comment by gertsonderby** [comment]
The problem only occurs when the component dialog or search page is in an iframe inside the existing console. I suspect it is an IE big more than anything else.

**Comment by gertsonderby** [comment]
Marcus mentioned that the console intercepts key presses to prevent e.g. history back on backspace. @neexite can you confirm if that might do something like this?

**Comment by wwwysocki** [comment]
Verified on 20170131.5 (dev)
