### ISSUE TITLE
Feature Branch Details

### ISSUE THREAD

**Issue by ai-fwd** [Orckestra/CMS-Foundation#374]
I noticed there are a lot of feature branches which is great to see but was wondering if there is a roadmap anywhere or any information you can share on what's going on with those branches?

**Comment by mawtex** [comment]
feature-widgetfactorymethod - merged into vnext-dev. This branch will be deleted soon.
Based on the issue you opened and @burningice2866's contribution. #314 #315 
 
feature-components - final bug fixing, will be merged into vnext-dev soon.
Feature which allow for a more user friendly way to add functions / html blocks to content. 

feature-console-search  - final bug fixing, will be merged into vnext-dev soon.
Search inside the console and on the website as well. Will ship first for open source with Lucene.NET support. 

vnext-dev - once we have major feature branches merged here and tested, this will go to dev,.
As the name implies the merge point for what will go into our next major release.

feature-message-queue-wamp - side project / prototyping.  
Replacing the periodic poll of messages from server to consoles with web sockets. We work on this if time allows.

feature-react-ui - we merge this to feature feature branches on occasion.
This is where major ground work on the new react ui is being done.
